### ISSUE TITLE
PETSc MR 6964 causes Channel fluids examples to fail

### ISSUE THREAD

**Issue by jrwrigh** [CEED/libCEED#1470]
*This is an already known failure (and the GitLab CI PETSc build has reverted that commit to allow tests to pass), but I've realized it never made it's way to a full issue and/or discussion on what the issue is or how to possibly address it.*

Starting with [PETSc MR 6964](https://gitlab.com/petsc/petsc/-/merge_requests/6964/), the Channel tests of the fluids example fail. 

My guess is that this has something to do with DMPlex's isoperiodicity, as that is the odd-feature-out between all the fluids tests and the Channel tests.

## What's (probably) happening
- the MR changed `PetscSectionFieldGetTensorDegree_Private` to get the degree of a tensor via it's `PetscDualSpace`.
- The only place `PetscSectionFieldGetTensorDegree_Private` is used is in `DMPlexSetClosurePermutationTensor`, which changes the ordering of the PetscSection DoF ordering to a tensor-product ordering

So as I see it, there are two possible ways the code is changing behavior:
- `PetscSectionFieldGetTensorDegree_Private` incorrectly reports the field as discontinuous
  - This is taken from `PetscDualSpaceLagrangeGetContinuity`
  - That function in turn gets it from a struct member, which is set in `PetscDualSpaceSetUp_Lagrange`
  - That function sets continuity based on the reported order of the dual space and whether it's `formDegree` matches the physical dimension. 
- `PetscSectionFieldGetTensorDegree_Private` does not calculate the tensor degree correctly
  - This is based on `PetscDualSpaceGetDimension`, which is in turn based on the size of the section associated with the PetscDualSpace
  
Unfortunately, I don't see an obvious place where isoperiodicity changes the DualSpace side of things. @jedbrown Any insight/ideas as to where to look?

Paging @rezgarshakeri since you made the PETSc MR.

Edit: The issue is not isoperiodicity per-say, but that periodicity requires using the Cell Coordinate DM, which then registers as discontinuous.

**Comment by knepley** [comment]
I fixed that stuff in https://gitlab.com/petsc/petsc/-/commit/5f82726afd598c9bfa8a3224245f704499d2c233

**Comment by jrwrigh** [comment]
I'm still seeing the issues on `main`, with that commit. These are with hex elements as well.

In https://github.com/CEED/libCEED/blob/72e72e0ec0f1356c4a8e31ae3520f998ca726cd1/examples/fluids/src/dm_utils.c#L490
we get that the dual space is `continuous == PETSC_FALSE`. Manually changing this to `PETSC_TRUE` everytime in gdb now makes the test successful.

Now, the fun part is I'm pretty sure the cell coordinate DualSpace _must_ be discontinuous (since that's kind of the point of the cell DM); feel free to correct me if I'm wrong on that part. 

Assuming that the CellDM should have a discontinuous DualSpace, I'm not sure if there needs to be an exception for cell coordinates in `DMPlexSetClosurePermutationTensor`/`PetscSectionFieldGetTensorDegree_Private`, or if there should be a change in the fluids example.

**Comment by jrwrigh** [comment]
Currently the code prefers getting the local coordinate array from the cell DM if it exists. So I think there needs to be some way of changing the ordering of the CellCoordinateDM's section to a tensor-product ordering.

**Comment by jrwrigh** [comment]
I noticed this comment in the PETSc MR:
> I added a continuity argument to `PetscSectionFieldGetTensorDegree_Private` so we change the permutation for continuous field only but I don't know how we can assign the perm array to the original permutation when the field is discontinuous.

What's the reason that discontinuous fields should keep their original permutation?

**Comment by rezgarshakeri** [comment]
> I noticed this comment in the PETSc MR:
> 
> > I added a continuity argument to `PetscSectionFieldGetTensorDegree_Private` so we change the permutation for continuous field only but I don't know how we can assign the perm array to the original permutation when the field is discontinuous.
> 
> What's the reason that discontinuous fields should keep their original permutation?

The permutation for discontinuous field is in a correct tensor ordering and we confirm that by mixed-elasticity in ratel.

**Comment by rezgarshakeri** [comment]
> I'm still seeing the issues on `main`, with that commit. These are with hex elements as well.
> 
> In
> 
> https://github.com/CEED/libCEED/blob/72e72e0ec0f1356c4a8e31ae3520f998ca726cd1/examples/fluids/src/dm_utils.c#L490
> 
> we get that the dual space is `continuous == PETSC_FALSE`. Manually changing this to `PETSC_TRUE` everytime in gdb now makes the test successful.
> 
> Now, the fun part is I'm pretty sure the cell coordinate DualSpace _must_ be discontinuous (since that's kind of the point of the cell DM); feel free to correct me if I'm wrong on that part.
> 
> Assuming that the CellDM should have a discontinuous DualSpace, I'm not sure if there needs to be an exception for cell coordinates in `DMPlexSetClosurePermutationTensor`/`PetscSectionFieldGetTensorDegree_Private`, or if there should be a change in the fluids example.

When I created that MR and MR after that by Matt, we didn't see any failure in periodic test cases in `ex8.c` petsc. We have these periodic tests
```
  test:
    suffix: 1d_q1_periodic
    requires: !complex
    args: -dm_plex_dim 1 -petscspace_degree 1 -dm_plex_simplex 0 -dm_plex_box_faces 3 -dm_plex_box_bd periodic -dm_view -view_coord
  test:
    suffix: 2d_q1_periodic
    requires: !complex
    args: -dm_plex_dim 2 -petscspace_degree 1 -dm_plex_simplex 0 -dm_plex_box_faces 3,2 -dm_plex_box_bd periodic,none -dm_view -view_coord
  test:
    suffix: 3d_q1_periodic
    requires: !complex
    args: -dm_plex_dim 3 -petscspace_degree 1 -dm_plex_simplex 0 -dm_plex_box_faces 3,2,1 -dm_plex_box_bd periodic,none,none -dm_view -view_coord
  test:
    suffix: 3d_q1_periodic_project
    requires: !complex
    args: -dm_plex_dim 3 -petscspace_degree 1 -dm_plex_simplex 0 -dm_plex_box_faces 1,1,3 -dm_plex_box_bd none,none,periodic -dm_view -view_coord -project_coordinates

  test:
    suffix: 3d_q2_periodic # not actually periodic because only 2 cells
    args: -dm_plex_dim 3 -petscspace_degree 2 -dm_plex_simplex 0 -dm_plex_box_faces 2,2,2 -dm_plex_box_bd periodic,none,periodic -dm_view
```
I think it would be better to reproduce this failure by a test case in `petsc/src/dm/impls/plex/tutorials/ex8.c`
